### ISSUE TITLE
GitHub Action deprecation notice - Please use `hashicorp/vault-action`

### ISSUE THREAD

**Issue by simenandre** [bjerkio/vault-action#393]
Thank you for using this Github Action!

There are few Open Source projects I've built which are deprecated as quickly as this Github Action, but it's for a good reason. Back in March of 2020, I built this as an alternative to @RichiCoder1's Github Action with the same name. Another reason was the lack of Github Authentication.

Open Source is better when we collaborate and help each other. We are invested in continuing our effort to make using Vault super easy for Github users, but we don't think maintaining an alternative to the official Vault Action no longer serve a purpose.

## Migrate to `hashicorp/vault-action`

Before:

```
- uses: bjerkio/vault-action@v1.2.1
  with:
    endpoint: https://vault.mycompany.com:8200
    path: 'kv/data/hello-world'
	githubToken: ${{ secrets.MY_GITHUB_TOKEN }}
```

After:

```
- name: Import Secrets
  uses: hashicorp/vault-action@v2.1.2
  with:
    url: https://vault.mycompany.com:8200
    githubToken: ${{ secrets.MY_GITHUB_TOKEN }}
    secrets: |
        kv/data/hello-world helloWorld | HELLO_WORLD ;
```

**Want help migrating to `hashicorp/vault-action`? Let us know below!**
